language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  api_key:
    secure: iMWTAFHc9bIa/f3EfigkXP9slGG8am6L/HhOQCWm4vc8SaqzgVBf0mzpkL8GnS8HHQoVOaN531nfOBlv/0yxVjDaoD//pKXH5PMSanPriF2xsilSwG1pIljcjFuFua0ksOGAbSxHBIGa6yz32ryTtCpe298zcPfCe9U2oVTpsnxgotixULNrQGj3jsQ6c/qsfCStwQMxjQs+Jlzvagtqez9vdkqwhHgT/klm0G2kAY8Z+sriESiqlJijnenE9Hk7AWuQL2j4dUU+c8LuHtdipBPZtFZLlMhrj8Lym4A/SazEvLD/3MlKKMVA13YMGTb4FKWaWhni2N+J0T/Fg459zL1zDziLInfl8k8g2rSrMCLC3zSf/1iWHf63vrQyYrWh1pbouQQZGW63O/TKuIidokHM3tsGN1YZxDMr8bY4kHNfZU2omRtYZvIJFZFWCT8bMdkaU5GwUU8TWssLVl2tWvyrZs5hlw0lPLNVvKikSDKoxvJD9/GOcp+8k2m51zC4Xo52YklGfnqKZdzxWPbSs1PohLnCnMJnBkeenyljWRv/zX6DMxK9KSxMkEpFGxcUdZGM7OEapcpGKgTakMgZQv16nlfn5KuKOmcLH5/4hsWgzbYxAULhN3rlAtTrAOWFgFvrK5+WK/o+pI8mRwNVgUOc7Kic/chJj1tcsmiHQfE=
  app: azmaria
  on:
    repo: louiedp3/angular-practice
