language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  api_key:
    secure: I/cp7GsROJF08MzGR7+cMmBRTb7TIsDJxdq0kz2NeLW8LA1IRoE8ZPaa0BQwNRcJIqM6KN6GIoxbEFoP38v9TXYLT28Llhry1y5vc8noG0VxAvYxIQDW6po9m6YH64rLQqXqmfpiZExFnGlUwx6WCOftnGxeOoJ7gMOBzx9p9VZ598p9qng2ZZIwoqVWbaITCDku7KAfZv218E2q7MA5IdB7tW7IOav9lINmCkNz2tzR8RsAFpSdIDxBiW4W9otPwb9ZnXUMs/pJtc3lLY0R0tfjZh3zCzWGRNeWJXy8g4MTCa52kX6lErLrZukKLJE7BSgMvzhxWx8LHLhslcDgVs40aF3DU85sgUp+9KgpGUU6716LV0kbU944ID09A4SmoTdu5QxDJlNAX0xHpKeTrV3nvAJJLKZRGm6WHM5nEE63aVaCkWUVYz0PSUjjZ5yVaBl75PIQPWYx2MefLmzBxOWEpg4QmYa+WrO/0PqsdCQ9H8AqfzWCg9hE3KAKcOggIMGZtBnbhPXnZv872FAm/5iRTlDqL6o9tDUu8fRBKT2VireQbXVQ6Wr4Ml07gOQRVEdwiGkkGIvlZBTMxU9ACTNEoqzvQbaBdM4hXX0vhAd314HuBWJcYNoNWfV4pBiUoZDLsGyDA/OWUsBPWMTVPXI//QlniE/g941prGIGSHg=
  app: azmaria
  on:
    repo: louiedp3/angular-practice
