language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  api_key:
    secure: di5Ka9TvmGpy1uK3Ooj/6wXFEOxg+BVoGQuC9+r/ZKkjDTLy75KUhXVI0ZgISQYpgqre2F20wsg1T5PePh8ALWEVogK5SqqwatrJ2mcFktKGhWcGizRt2uUWjNzX6IhdmmVe1zYv0ocJ7CJc+xV1o8V+XXhGyS4+6221xCtiioHiHSUOcfkjS0jMYU4a+TGIw6bAes7+NVR5euxiZINKgwVSIzPaO6lzWkjpsggOdBYJmlScdlyIguTEdg29itk+Jfc8z7oW/N95URVGKapBXbfyWkRkZaQQacaQJQczzcvSf56y5sJxAWpTW1zAXKleNLcrzKlp9f3aWoLLEoJ0IgBIVTgZYxXkbKN+JazmBSH6+rxKacQHL7+8C5O00NwU6wcoiFT5nA9g9wTuGLBZUeKWIaUnJyyPUNzcufoZMrZMnIqLpz3gq14dT4Gm6k/dN3D5tOfWZyXjH55l55U+SKJvLIPXHONZvRDKfb8bAXbzC1G6lMjJ308FZxt1yqgdb8EyrvBxRlyE2KZTXKWlNn/kCtD/nzisDr4mQ3ZgADcjT8rhQRYHtkFXwD+ddz03BEaNaS5VkL2D27if2YkFgQlF2zovLGaHnrF4GIr/nVDIJviHRMW4SY3bT+9aaEkYp8Hw+T2L2jV0pg8ZCgpWnQ8Kicsh8WMJNIOusykqse4=
  app: hey-listen
  on:
    repo: louiedp3/angular-practice
